webOS-ports/webos-keyboard

src/plugin/inputmethod.cpp
=> Fix orientation of keyboard window mask

qml/keys/ExtendedKeysSelector.qml
=> Keys: fix the extended key selector background image

qml/keys/ActionKey.qml, qml/keys/AnnotatedKey.qml, qml/keys/CharKey.qml, qml/keys/ExtendedKeysSelector.qml, qml/keys/GreyKey.qml, qml/keys/Magnifier.qml, qml/keys/ShiftKey.qml, qml/keys/key_constants.js, tests/qmltests/keyboard-test/keyboard-test/keyboard-test.qml
+ flexible layout of the test program based on Settings stub. Changed color for selected annotation to blue instead of orange as per legacy.
=> Initial work for different font colors for tablet and phone

tests/qmltests/keyboard-test/keyboard-test/keyboard-test.qml
=> Tests: add a button to switch the current form factor (phone or tablet)

qml/keys/AnnotatedKey.qml
=> Fix top-row extended list

qml/keys/Magnifier.qml, qml/keys/key_constants.js
=> Fix magnifier font size

plugins/en/qml/Keyboard_en_phone.qml, plugins/en/qml/Keyboard_en_phone_email.qml, plugins/en/qml/Keyboard_en_phone_url_search.qml, plugins/en/qml/Keyboard_en_tablet.qml, plugins/en/qml/Keyboard_en_tablet_email.qml, plugins/en/qml/Keyboard_en_tablet_url_search.qml, qml/keys/ActionKey.qml, qml/keys/AnnotatedKey.qml, qml/keys/CharKey.qml, qml/keys/ExtendedListSelector.qml, qml/keys/Magnifier.qml, qml/keys/NumKey.qml, qml/keys/ReturnKey.qml, qml/keys/SymbolShiftKey.qml, qml/keys/TabKey.qml, qml/keys/UI.qml, qml/keys/UrlKey.qml, qml/keys/key_constants.js
This should fix the S and XS behavior for tablet layouts (more similar to legacy) + further enhance the phone layouts as well.
=> Various layout tweaks

qml/keys/AnnotatedKey.qml
=> AnnotatedKey: fix submit of value

qml/keys/UI.qml, qml/keys/key_constants.js
=> Correct order of key height labels

qml/Tweak.qml, tests/keyboard-test/LuneOS/Service/LunaService.qml, tests/keyboard-test/LuneOS/Service/LunaServiceRegistering.js, tests/keyboard-test/LuneOS/Service/qmldir
=> Tweaks: add initial support

qml/keys/ExtendedListSelector.qml, qml/keys/KeyPad.qml, qml/keys/TrackBall.qml
Prevent swiping down keyboard while using the trackball
=> Prevent swiping down keyboard while using the trackball

qml/keys/AnnotatedKey.qml, qml/keys/CharKey.qml, qml/keys/GreyKey.qml, qml/keys/PressArea.qml
=> Make the PressArea more reliable

plugins/en/qml/Keyboard_en_tablet.qml, qml/keys/NumKey.qml, qml/keys/UI.qml, qml/keys/key_constants.js, qml/languages/Keyboard_symbols_tablet.qml
Cleanup symbols layout to be similar to regular layout. Using flexible
ratios instead of hardcoded values for toprow key width and height.
=> Symbols layout unification + flexible approach for toprow

plugins/ar/qml/Keyboard_ar_phone.qml, plugins/ar/qml/Keyboard_ar_tablet.qml, plugins/da/qml/Keyboard_da_phone.qml, plugins/da/qml/Keyboard_da_tablet.qml, plugins/de/qml/Keyboard_de_phone.qml, plugins/de/qml/Keyboard_de_tablet.qml, plugins/en/qml/Keyboard_en_phone.qml, plugins/en/qml/Keyboard_en_tablet.qml, plugins/en/qml/Keyboard_en_tablet_thumb.qml, plugins/fr/qml/Keyboard_fr_phone.qml, plugins/fr/qml/Keyboard_fr_tablet.qml, plugins/ru/qml/Keyboard_ru_phone.qml, qml/languages/Keyboard_symbols_phone.qml
-Shifted symbol layout on phones fixed
-Initial work for Arabic layout
-Additional extended characters to support Slavic languages like Czech has been added to the other language layouts.
=> Fix shifted symbol layout, initial work for Arabic + additional extended characters

qml/keys/MultiTouchKeyArea.qml
=> Fix long press on keys with "..."

src/plugin/keyboardsettings.cpp, src/plugin/keyboardsettings.h
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
=> Fix typos mSpellchecing -> mSpellchecking

service/org.maliit.json.prv
=> Fix LS2 permissions for "" service name

qml/keys/Magnifier.qml
=> Magnifer: fix background tile image

files/sysbus/org.maliit.perm.json, files/sysbus/org.maliit.role.json, src/plugin/keyboardsettings.cpp
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
=> webos-keyboard: Migrate to LS2 ACG model

qml/keys/AnnotatedKey.qml, qml/keys/CharKey.qml
For a 48x48 image, a BorderImage doesn't work well if left+right==48
=> keys: fix BorderImage dimensions

files/sysbus/org.maliit.perm.json, qml/Keyboard.qml, qml/keys/AnnotatedKey.qml, qml/keys/CharKey.qml, qml/keys/GreyKey.qml, qml/keys/KeyPad.qml, qml/keys/ShiftKey.qml
Fixes ACG permissions and warnings about implicitly declared functions with Qt 5.15.
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
=> Qt5.15 & ACG fix

src/plugin/inputmethod.cpp, src/plugin/plugin.cpp
Another complementary fix is also need in Maliit's server config file to finish the fix
=> Fix hw keyboard
